{ pkgs, lib, ... }:
# Ghostty terminal config, shared by macOS (app from the brew cask) and the
# server's GNOME desktop (package added in hosts/server/configuration.nix).
# TokyoNight with explicit palette overrides; originally generated by the
# "Ghostty Config" web generator.
let
  ghosttyConfig = ''
    font-size = 14
    background-opacity = 0.88
    background-blur = true
    theme = TokyoNight
    background = #1a1b26
    foreground = #c0caf5
    selection-background = #33467c
    selection-foreground = #c0caf5
    cursor-color = #c0caf5
    cursor-text = #15161e
    palette = 0=#15161e
    palette = 1=#f7768e
    palette = 2=#9ece6a
    palette = 3=#e0af68
    palette = 4=#7aa2f7
    palette = 5=#bb9af7
    palette = 6=#7dcfff
    palette = 7=#a9b1d6
    palette = 8=#414868
    palette = 9=#f7768e
    palette = 10=#9ece6a
    palette = 11=#e0af68
    palette = 12=#7aa2f7
    palette = 13=#bb9af7
    palette = 14=#7dcfff
    palette = 15=#c0caf5
  ''
  # macOS-only key — on Linux it would show up as a config error at launch.
  + lib.optionalString pkgs.stdenv.isDarwin ''
    macos-icon = blueprint
  '';
in
{
  # Linux: Ghostty reads $XDG_CONFIG_HOME/ghostty/config.
  xdg.configFile."ghostty/config" = lib.mkIf pkgs.stdenv.isLinux {
    text = ghosttyConfig;
  };

  # macOS: the native location is ~/Library/Application Support/com.mitchellh.ghostty/config.
  # NOTE the filename must be exactly `config` — a `config.ghostty` in that
  # directory is silently ignored by Ghostty.
  home.file."Library/Application Support/com.mitchellh.ghostty/config" =
    lib.mkIf pkgs.stdenv.isDarwin {
      text = ghosttyConfig;
    };
}
